import Image from "next/image";
import React from "react";
import { SectionWrapper } from "../wrapper/section-wrapper";
import { Generator } from "../elements/generator";

const Hero = () => {
  return (
    <section className="relative pt-[121px] xl:pt-[151px] 2xl:pt-[231px] pb-[63px] lg:pb-[93px] xl:pb-[113px]">
      <div className="absolute select-none w-full h-full top-0 start-0 before:absolute before:content-[''] before:w-full before:h-full before:top-0 before:start-0 before:bg-gradient-180 before:from-[#05111900] before:from-0% before:to-[#051119] before:to-[129.9%]">
        <Image
          width={1920}
          height={920}
          src="/Assets/hero/shape-1.png"
          className="object-cover"
          alt="bg image"
        />
      </div>
      <SectionWrapper className="container relative z-[2] text-center">
        <h1 className="text-[34px] md:text-[50px] xl:text-[70px] 2xl:text-[110px] max-w-[410px] md:max-w-[510px] xl:max-w-[710px] 2xl:max-w-[1010px] mx-auto !font-bold !leading-[1.09] [&>span]:bg-gradient-160 [&>span]:from-[#C581FB] [&>span]:from-[48.22%] [&>span]:to-[#FFAD93] [&>span]:to-[71.11%] [&>span]:bg-clip-text [&>span]:text-transparent [&>img]:-me-[20px] xl:[&>img]:-me-[30px] 2xl:[&>img]:-me-[50px] [&>img]:hidden md:[&>img]:w-[76px] md:[&>img]:inline-block xl:[&>img]:w-[100px] 2xl:[&>img]:w-[160px] [&>img]:rtl_y has_fade_anim">
          Professional <span className="[&>span]:bg-gradient-160 [&>span]:from-[#C581FB] [&>span]:from-[48.22%] [&>span]:to-[#FFAD93] [&>span]:to-[71.11%] [&>span]:bg-clip-text [&>span]:text-transparent ">AI</span> Ads videos in minutes
        </h1>
        <p className='mt-[20px] text-[20px] 2xl:text-[24px] leading-[1.33] max-w-[530px] 2xl:max-w-[760px] mx-auto has_fade_anim'
				data-delay='0.30'>
          Elevate your online presence with Ads Video Generated by Our AI
        </p>
        <div className='mt-[36px] xl:mt-[46px] 2xl:mt-[56px]'>
				<Generator />
			</div>
      </SectionWrapper>
    </section>
  );
};

export default Hero;
