import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import "./globals.css";
import { Footer } from '@/components/elements/footer'
import { AuthProvider } from "@/context/GlobalContect";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { publicFooterLinks } from '@/data/site-info'


export const metadata: Metadata = {
  title: "Ads Video AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className=' overflow-hidden mx-auto bg-[#05111A]'>
        <AuthProvider>
          <Header />
          {children}
          <ToastContainer />
          <Footer footerNav={publicFooterLinks} />
        </AuthProvider>
        </div>
      </body>
    </html>
  );
}
